name: Unity Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build Unity Game
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Cache Library
        uses: actions/cache@v3
        with:
          path: Library
          key: Library-${{ runner.os }}-${{ github.sha }}
          restore-keys: |
            Library-${{ runner.os }}-

      - name: Install Unity
        uses: game-ci/unity-builder@v3
        with:
          unityVersion: 2021.3.18f1 # Change this to your Unity version

      - name: Build project
        uses: game-ci/unity-builder@v3
        with:
          unityVersion: 2021.3.18f1
          targetPlatform: StandaloneWindows64

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Matatu-Game
          path: build
